CREATE SEQUENCE tag_seq START WITH 1;

CREATE OR REPLACE FUNCTION gen_id(planet_name VARCHAR)
RETURNS VARCHAR
LANGUAGE plpgsql
AS
$$
DECLARE short_name VARCHAR;
BEGIN
	SELECT UPPER(CONCAT(SUBSTRING(planet_name FOR 4), CAST(NEXTVAL('tag_seq') AS VARCHAR))) INTO short_name;
	RETURN short_name;
END;
$$
IMMUTABLE;

CREATE TABLE planet (
id VARCHAR UNIQUE NOT NULL GENERATED ALWAYS AS (gen_id(name)) STORED,
name VARCHAR(500) NOT NULL,
PRIMARY KEY (id)
);